# Generated by Django 4.2.14 on 2024-07-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='username',
        ),
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(default='<YOUR NAME HERE>', max_length=255),
        ),
    ]
