# Generated by Django 4.2.14 on 2024-07-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_hero_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='icon',
        ),
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
