# Generated by Django 4.2.14 on 2024-07-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contact_icon_alter_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/core/me/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cv',
            field=models.ImageField(upload_to='static/core/cv/'),
        ),
    ]
