# Generated by Django 4.2.9 on 2024-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hero_image_alter_hero_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/core/contactlogos/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
