# Generated by Django 4.2.9 on 2024-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_logo_file_contact_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='static/core/contactlogos/'),
        ),
    ]
