# Generated by Django 4.2.9 on 2024-07-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contact_logo_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactItem',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
