# Generated by Django 4.2.9 on 2024-07-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_contact_contactitem_delete_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.section')),
                ('title1', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle1', models.CharField(blank=True, max_length=255, null=True)),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts', models.ManyToManyField(blank=True, to='core.contactitem')),
            ],
        ),
    ]
