# Generated by Django 4.2.9 on 2024-07-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_portfolioitem_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('image', models.ImageField(upload_to='static/core/skills')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='static/core/portfolio_images/'),
        ),
        migrations.CreateModel(
            name='SkillsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('skills_items', models.ManyToManyField(to='core.skillitem')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.section')),
                ('topics', models.ManyToManyField(to='core.skillstopic')),
            ],
        ),
    ]
