# Generated by Django 4.2.9 on 2024-07-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_skillitem_alter_portfolioitem_image_skillstopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ImageField(upload_to='static/core/cv/')),
            ],
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='image',
            field=models.FileField(upload_to='static/core/skills'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cv'),
        ),
    ]
