# Generated by Django 4.2.9 on 2024-07-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cv_alter_skillitem_image_alter_hero_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='cv',
        ),
    ]
