# Generated by Django 4.2.9 on 2024-07-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_hero_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.section')),
                ('content', models.TextField()),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cv')),
            ],
        ),
    ]
