# Generated by Django 4.2.9 on 2024-07-29 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='link_to_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_link_to_section', to='core.section'),
        ),
    ]
