# Generated by Django 4.2.9 on 2024-07-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_hero_link_to_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aside',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.section')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
