# Generated by Django 4.2.9 on 2024-07-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aside'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aside',
        ),
    ]
