# Generated by Django 4.2.9 on 2024-07-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_asidelink_aside'),
    ]

    operations = [
        migrations.AddField(
            model_name='asidelink',
            name='name',
            field=models.CharField(default='<LINK NAME HERE>', max_length=99),
        ),
    ]
