# Generated by Django 4.2.9 on 2024-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_asidelink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aside',
            name='name',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
