# Generated by Django 4.2.14 on 2024-07-30 21:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_aside_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField()),
                ('light_mode', models.BooleanField()),
                ('color1', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('color2', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('color3', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('color4', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('color5', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
        ),
    ]
