# Generated by Django 4.2.14 on 2024-07-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_themecolors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.FileField(upload_to='static/core/cv/'),
        ),
    ]
